project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"commit_message": "[ci skip]"

files:
  - source: /docs/*.md
    translation: /docs/%locale%/%original_file_name%
  - source: /README.md
    translation: /docs/%locale%/%original_file_name%
